config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # A visitor can see the list of all restaurants.
  # GET "restaurants"
  # A visitor can add a new restaurant, and be redirected to the show view of that new restaurant.
  # GET "restaurants/new"
  # POST "restaurants"
  # A visitor can see the details of a restaurant, with all the reviews related to the restaurant.
  # GET "restaurants/38"
  # resources :restaurants
  resources :restaurants, only: [:index, :new, :create, :show] do
    # A visitor can add a new review to a restaurant
    # GET "restaurants/38/reviews/new"
    # POST "restaurants/38/reviews"
    resources :reviews, only: [:index, :new, :create]
  end

  resources :reviews, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :category, presence: true
  validates :address, presence: true
  validates :category, inclusion: { in: %w[chinese italian japanese french belgian], message: 'Not a valid category' }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, numericality: { greater_than_or_equal_to: 0 }
  validates :rating, numericality: { less_than_or_equal_to: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :find_restaurant, only: [ :show ]

  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def show
  end

  private

  def find_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit([:name, :address, :phone_number, :category])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, only: [:index, :new, :create]
  def index
    @reviews = @restaurant.reviews
  end

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to restaurant_path(@review.restaurant)
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit([:rating, :content])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Add these line for detecting device width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container pt-4">
      <%= yield %>
    </div>
  </body>
</html>

app/views/restaurants/index.html.erb
<div class="d-flex">
  <h1 class="flex-grow-1">Restaurants</h1>
  <%= link_to 'Add new restaurant', new_restaurant_path, class: 'btn btn-primary' %>
</div>
<ul class="list-unstyled">
<% @restaurants.each do |restaurant| %>
  <li>
    <%= link_to restaurant.name, restaurant_path(restaurant) %>
    -
    <%= restaurant.category.capitalize %>
  </li>
<% end %>
</ul>

app/views/restaurants/new.html.erb
<h1>New restaurant</h1>
<%= simple_form_for @restaurant do |f| %>
  <%= f.input :name %>
  <%= f.input :category %>
  <%= f.input :phone_number %>
  <%= f.input :address %>
  <%= f.submit "Create restaurant", class: "btn btn-primary" %>
<% end %>

app/views/restaurants/show.html.erb
<h1><strong><%= @restaurant.name %></strong></h1>

<h3><strong>Informations:</strong></h3>
<p><strong>Category:</strong> <%= @restaurant.category %></p>
<p><strong>Address:</strong> <%= @restaurant.address %></p>
<p><strong>Phone number:</strong> <%= @restaurant.phone_number %></p>

<div class="d-flex pb-3">
  <h3 class="flex-grow-1">Reviews</h3>
  <%= link_to 'Add a review', new_restaurant_review_path(@restaurant), class: 'btn btn-primary' %>
</div>

<ul class="list-unstyled">
<% @restaurant.reviews.each do |review| %>
  <li class="list-group-item d-flex mr-2 ml-2">
    <div class="flex-grow-1"><strong><%= review.rating %>/5</strong> - <%= review.content.capitalize %></div>

    <%= link_to review_path(review), method: :delete, data: { confirm: "Are you sure?" } do %>
      <i class="fa fa-trash"></i>
    <% end %>
  </li>
<% end %>
</ul>

app/views/reviews/new.html.erb
  <h1>New review</h1>
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :rating %>
  <%= f.input :content %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>